name: aimart_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  image_picker_web: ^3.0.0+1
  flutter_screenutil: ^5.5.4
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  animated_splash_screen: ^1.3.0
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.1.2
  flutter_admin_scaffold: ^1.1.2
  multi_select_flutter: ^4.1.2
  universal_html: ^2.0.8
  uuid: ^3.0.6
  algolia: ^1.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/

