name: aimart_admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  image_picker_web: ^2.1.1
  flutter_screenutil: ^5.5.4
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.5
  animated_splash_screen: ^1.3.0
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  firebase_storage: ^10.3.11
  flutter_admin_scaffold: ^1.1.2
  multi_select_flutter: ^4.1.2
  universal_html: ^2.0.8

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/

